Insert into Pays (Nom) values ('S/N');
Insert into Pays (Nom) values ('Afghanistan');
Insert into Pays (Nom) values ('Afrique du Sud');
Insert into Pays (Nom) values ('Albanie');
Insert into Pays (Nom) values ('Algérie');
Insert into Pays (Nom) values ('Allemagne');
Insert into Pays (Nom) values ('Andorre');
Insert into Pays (Nom) values ('Angola');
Insert into Pays (Nom) values ('Anguilla');
Insert into Pays (Nom) values ('Antigua-et-Barbuda');
Insert into Pays (Nom) values ('Antilles Néerlandaises');
Insert into Pays (Nom) values ('Arabie Saoudite');
Insert into Pays (Nom) values ('Argentine');
Insert into Pays (Nom) values ('Arménie');
Insert into Pays (Nom) values ('Aruba');
Insert into Pays (Nom) values ('Australie');
Insert into Pays (Nom) values ('Autriche');
Insert into Pays (Nom) values ('Azerbaïdjan');
Insert into Pays (Nom) values ('Bahamas');
Insert into Pays (Nom) values ('Bahreïn');
Insert into Pays (Nom) values ('Bangladesh');
Insert into Pays (Nom) values ('Barbade');
Insert into Pays (Nom) values ('Belgique');
Insert into Pays (Nom) values ('Belize');
Insert into Pays (Nom) values ('Bénin');
Insert into Pays (Nom) values ('Bermudes');
Insert into Pays (Nom) values ('Bhoutan');
Insert into Pays (Nom) values ('Biélorussie');
Insert into Pays (Nom) values ('Birmanie (Myanmar)');
Insert into Pays (Nom) values ('Bolivie');
Insert into Pays (Nom) values ('Bosnie-Herzégovine');
Insert into Pays (Nom) values ('Botswana');
Insert into Pays (Nom) values ('Brésil');
Insert into Pays (Nom) values ('Brunei');
Insert into Pays (Nom) values ('Bulgarie');
Insert into Pays (Nom) values ('Burkina Faso');
Insert into Pays (Nom) values ('Burundi');
Insert into Pays (Nom) values ('Cambodge');
Insert into Pays (Nom) values ('Cameroun');
Insert into Pays (Nom) values ('Canada');
Insert into Pays (Nom) values ('Cap-vert');
Insert into Pays (Nom) values ('Chili');
Insert into Pays (Nom) values ('Chine');
Insert into Pays (Nom) values ('Chypre');
Insert into Pays (Nom) values ('Colombie');
Insert into Pays (Nom) values ('Comores');
Insert into Pays (Nom) values ('Corée du Nord');
Insert into Pays (Nom) values ('Corée du Sud');
Insert into Pays (Nom) values ('Costa Rica');
Insert into Pays (Nom) values ("Côte d'Ivoire");
Insert into Pays (Nom) values ('Croatie');
Insert into Pays (Nom) values ('Cuba');
Insert into Pays (Nom) values ('Danemark');
Insert into Pays (Nom) values ('Djibouti');
Insert into Pays (Nom) values ('Dominique');
Insert into Pays (Nom) values ('Égypte');
Insert into Pays (Nom) values ('Émirats Arabes Unis');
Insert into Pays (Nom) values ('Équateur');
Insert into Pays (Nom) values ('Érythrée');
Insert into Pays (Nom) values ('Espagne');
Insert into Pays (Nom) values ('Estonie');
Insert into Pays (Nom) values ('États Fédérés de Micronésie');
Insert into Pays (Nom) values ('États-Unis');
Insert into Pays (Nom) values ('Éthiopie');
Insert into Pays (Nom) values ('Fidji');
Insert into Pays (Nom) values ('Finlande');
Insert into Pays (Nom) values ('France');
Insert into Pays (Nom) values ('Gabon');
Insert into Pays (Nom) values ('Gambie');
Insert into Pays (Nom) values ('Géorgie');
Insert into Pays (Nom) values ('Géorgie du Sud et les Îles Sandwich du Sud');
Insert into Pays (Nom) values ('Ghana');
Insert into Pays (Nom) values ('Gibraltar');
Insert into Pays (Nom) values ('Grèce');
Insert into Pays (Nom) values ('Grenade');
Insert into Pays (Nom) values ('Groenland');
Insert into Pays (Nom) values ('Guadeloupe');
Insert into Pays (Nom) values ('Guam');
Insert into Pays (Nom) values ('Guatemala');
Insert into Pays (Nom) values ('Guinée');
Insert into Pays (Nom) values ('Guinée Équatoriale');
Insert into Pays (Nom) values ('Guinée-Bissau');
Insert into Pays (Nom) values ('Guyana');
Insert into Pays (Nom) values ('Guyane Française');
Insert into Pays (Nom) values ('Haïti');
Insert into Pays (Nom) values ('Honduras');
Insert into Pays (Nom) values ('Hong-Kong');
Insert into Pays (Nom) values ('Hongrie');
Insert into Pays (Nom) values ('Île Christmas');
Insert into Pays (Nom) values ('Île de Man');
Insert into Pays (Nom) values ('Île Norfolk');
Insert into Pays (Nom) values ('Îles Åland');
Insert into Pays (Nom) values ('Îles Caïmanes');
Insert into Pays (Nom) values ('Îles Cocos (Keeling)');
Insert into Pays (Nom) values ('Îles Cook');
Insert into Pays (Nom) values ('Îles Féroé');
Insert into Pays (Nom) values ('Îles Malouines');
Insert into Pays (Nom) values ('Îles Mariannes du Nord');
Insert into Pays (Nom) values ('Îles Marshall');
Insert into Pays (Nom) values ('Îles Pitcairn');
Insert into Pays (Nom) values ('Îles Salomon');
Insert into Pays (Nom) values ('Îles Turks et Caïques');
Insert into Pays (Nom) values ('Îles Vierges Britanniques');
Insert into Pays (Nom) values ('Îles Vierges des États-Unis');
Insert into Pays (Nom) values ('Inde');
Insert into Pays (Nom) values ('Indonésie');
Insert into Pays (Nom) values ('Iran');
Insert into Pays (Nom) values ('Iraq');
Insert into Pays (Nom) values ('Irlande');
Insert into Pays (Nom) values ('Islande');
Insert into Pays (Nom) values ('Israël');
Insert into Pays (Nom) values ('Italie');
Insert into Pays (Nom) values ('Jamaïque');
Insert into Pays (Nom) values ('Japon');
Insert into Pays (Nom) values ('Jordanie');
Insert into Pays (Nom) values ('Kazakhstan');
Insert into Pays (Nom) values ('Kenya');
Insert into Pays (Nom) values ('Kirghizistan');
Insert into Pays (Nom) values ('Kiribati');
Insert into Pays (Nom) values ('Koweït');
Insert into Pays (Nom) values ('Laos');
Insert into Pays (Nom) values ('Le Vatican');
Insert into Pays (Nom) values ('Lesotho');
Insert into Pays (Nom) values ('Lettonie');
Insert into Pays (Nom) values ('Liban');
Insert into Pays (Nom) values ('Libéria');
Insert into Pays (Nom) values ('Libye');
Insert into Pays (Nom) values ('Liechtenstein');
Insert into Pays (Nom) values ('Lituanie');
Insert into Pays (Nom) values ('Luxembourg');
Insert into Pays (Nom) values ('Macao');
Insert into Pays (Nom) values ('Madagascar');
Insert into Pays (Nom) values ('Malaisie');
Insert into Pays (Nom) values ('Malawi');
Insert into Pays (Nom) values ('Maldives');
Insert into Pays (Nom) values ('Mali');
Insert into Pays (Nom) values ('Malte');
Insert into Pays (Nom) values ('Maroc');
Insert into Pays (Nom) values ('Martinique');
Insert into Pays (Nom) values ('Maurice');
Insert into Pays (Nom) values ('Mauritanie');
Insert into Pays (Nom) values ('Mayotte');
Insert into Pays (Nom) values ('Mexique');
Insert into Pays (Nom) values ('Moldavie');
Insert into Pays (Nom) values ('Monaco');
Insert into Pays (Nom) values ('Mongolie');
Insert into Pays (Nom) values ('Monténégro');
Insert into Pays (Nom) values ('Montserrat');
Insert into Pays (Nom) values ('Mozambique');
Insert into Pays (Nom) values ('Namibie');
Insert into Pays (Nom) values ('Nauru');
Insert into Pays (Nom) values ('Népal');
Insert into Pays (Nom) values ('Nicaragua');
Insert into Pays (Nom) values ('Niger');
Insert into Pays (Nom) values ('Nigéria');
Insert into Pays (Nom) values ('Niué');
Insert into Pays (Nom) values ('Norvège');
Insert into Pays (Nom) values ('Nouvelle-Calédonie');
Insert into Pays (Nom) values ('Nouvelle-Zélande');
Insert into Pays (Nom) values ('Oman');
Insert into Pays (Nom) values ('Ouganda');
Insert into Pays (Nom) values ('Ouzbékistan');
Insert into Pays (Nom) values ('Pakistan');
Insert into Pays (Nom) values ('Palaos');
Insert into Pays (Nom) values ('Panama');
Insert into Pays (Nom) values ('Papouasie-Nouvelle-Guinée');
Insert into Pays (Nom) values ('Paraguay');
Insert into Pays (Nom) values ('Pays-Bas');
Insert into Pays (Nom) values ('Pérou');
Insert into Pays (Nom) values ('Philippines');
Insert into Pays (Nom) values ('Pologne');
Insert into Pays (Nom) values ('Polynésie Française');
Insert into Pays (Nom) values ('Porto Rico');
Insert into Pays (Nom) values ('Portugal');
Insert into Pays (Nom) values ('Qatar');
Insert into Pays (Nom) values ('République Centrafricaine');
Insert into Pays (Nom) values ('République de Macédoine');
Insert into Pays (Nom) values ('République Démocratique du Congo');
Insert into Pays (Nom) values ('République Dominicaine');
Insert into Pays (Nom) values ('République du Congo');
Insert into Pays (Nom) values ('République Tchèque');
Insert into Pays (Nom) values ('Réunion');
Insert into Pays (Nom) values ('Roumanie');
Insert into Pays (Nom) values ('Royaume-Uni');
Insert into Pays (Nom) values ('Russie');
Insert into Pays (Nom) values ('Rwanda');
Insert into Pays (Nom) values ('Sainte-Hélène');
Insert into Pays (Nom) values ('Sainte-Lucie');
Insert into Pays (Nom) values ('Saint-Kitts-et-Nevis');
Insert into Pays (Nom) values ('Saint-Marin');
Insert into Pays (Nom) values ('Saint-Pierre-et-Miquelon');
Insert into Pays (Nom) values ('Saint-Vincent-et-les Grenadines');
Insert into Pays (Nom) values ('Salvador');
Insert into Pays (Nom) values ('Samoa');
Insert into Pays (Nom) values ('Samoa Américaines');
Insert into Pays (Nom) values ('Sao Tomé-et-Principe');
Insert into Pays (Nom) values ('Sénégal');
Insert into Pays (Nom) values ('Serbie');
Insert into Pays (Nom) values ('Seychelles');
Insert into Pays (Nom) values ('Sierra Leone');
Insert into Pays (Nom) values ('Singapour');
Insert into Pays (Nom) values ('Slovaquie');
Insert into Pays (Nom) values ('Slovénie');
Insert into Pays (Nom) values ('Somalie');
Insert into Pays (Nom) values ('Soudan');
Insert into Pays (Nom) values ('Sri Lanka');
Insert into Pays (Nom) values ('Suède');
Insert into Pays (Nom) values ('Suisse');
Insert into Pays (Nom) values ('Suriname');
Insert into Pays (Nom) values ('Svalbard et Jan Mayen');
Insert into Pays (Nom) values ('Swaziland');
Insert into Pays (Nom) values ('Syrie');
Insert into Pays (Nom) values ('Tadjikistan');
Insert into Pays (Nom) values ('Taïwan');
Insert into Pays (Nom) values ('Tanzanie');
Insert into Pays (Nom) values ('Tchad');
Insert into Pays (Nom) values ('Terres Australes Françaises');
Insert into Pays (Nom) values ('Thaïlande');
Insert into Pays (Nom) values ('Timor Oriental');
Insert into Pays (Nom) values ('Togo');
Insert into Pays (Nom) values ('Tonga');
Insert into Pays (Nom) values ('Trinité-et-Tobago');
Insert into Pays (Nom) values ('Tunisie');
Insert into Pays (Nom) values ('Turkménistan');
Insert into Pays (Nom) values ('Turquie');
Insert into Pays (Nom) values ('Tuvalu');
Insert into Pays (Nom) values ('Ukraine');
Insert into Pays (Nom) values ('Uruguay');
Insert into Pays (Nom) values ('Vanuatu');
Insert into Pays (Nom) values ('Venezuela');
Insert into Pays (Nom) values ('Viet Nam');
Insert into Pays (Nom) values ('Wallis et Futuna');
Insert into Pays (Nom) values ('Yémen');
Insert into Pays (Nom) values ('Zambie');
Insert into Pays (Nom) values ('Zimbabwe');
